# ==== CONFIGURE =====
# Use a Node 16 base image
FROM node:19-alpine 
# Set the working directory to /app inside the container
WORKDIR /app
# Copy app files
COPY package*.json .

# ==== BUILD =====
# Install dependencies (npm cai makes sure the exact versions in the lockfile gets installed)
RUN npm ci 

# ==== RUN =======
# Set the env to "production"
ENV NODE_ENV dev
# Expose the port on which the app will be running (3000 is the default that `serve` uses)
EXPOSE 9000

# Start the app
CMD [ "npm", "run" ,"start"]